/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * Find the sum of all the even-valued terms in the sequence which do not exceed four million.
 */
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>

unsigned long long int fib(void){
    unsigned long long int x,y,res,sum;
    x = sum = 0;
    res = y = 1;
    int limit = 4000000;
    while(res <= limit){
        res = x + y;
        x = y;
        y = res;
        if(res%2==0){
            sum += res;
            printf("\nsum: %lld", sum);
        }
        printf("\nres: %lld", res);
    }
    return sum;
}

int main (int argc, char *argv[]){
    printf("\n%lld\n", fib());
    return 1;
}
